heuristic:
  function:
    grader:
      coefficient:
        method:
          collective: 1
          zeros: 3
          heights: 4
          axis:
            x: 1
            y: 1
            z: 1